# Generated by Django 3.2.9 on 2021-12-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name='Возраст'),
        ),
    ]
